import type { RouteObject } from "react-router-dom";
import { Layout } from "./components/Layout";
import { OrganizerAppLayout } from "./components/OrganizerAppLayout";
import { UserAppLayout } from "./components/UserAppLayout";
import { LandingPage } from "./pages/LandingPage";
import { LoginPage } from "./pages/LoginPage";
import { RegisterPage } from "./pages/RegisterPage";
import {
  AdminBlockchainLogPage,
  AdminDashboardPage,
  AdminDisputeTransactionPage,
  AdminEventManagePage,
  AdminLoginPage,
  AdminUserManagePage,
  CheckInManagePage,
  EventCreatePage,
  EventDetailPage,
  EventListPage,
  EventSettingsPage,
  MyTicketListPage,
  OrganizerAuthPage,
  OrganizerDashboardPage,
  OrganizerEventDetailPage,
  OrganizerEventListPage,
  OrganizerLandingPage,
  OrganizerProfilePage,
  OrganizerApprovalPage,
  PurchaseCompletePage,
  ResaleDetailPage,
  ResaleListPage,
  ResaleRegisterCompletePage,
  SalesStatusPage,
  TicketDetailPage,
  TicketIssuePage,
  TicketPurchasePage,
  TicketQrPage,
  TicketResaleCreatePage,
  UserAuthPage,
  UserHomePage,
  UserLandingPage,
  UserMyPage,
} from "./pages/portalPages";

export const appRoutes: RouteObject[] = [
  {
    path: "/",
    element: <Layout />,
    children: [
      { index: true, element: <LandingPage /> },
      { path: "login", element: <LoginPage /> },
      { path: "register", element: <RegisterPage /> },
      {
        path: "app",
        element: <UserAppLayout />,
        children: [
          { index: true, element: <UserLandingPage /> },
          { path: "auth", element: <UserAuthPage /> },
          { path: "home", element: <UserHomePage /> },
          { path: "events", element: <EventListPage /> },
          { path: "events/:eventId", element: <EventDetailPage /> },
          { path: "tickets/:ticketId/purchase", element: <TicketPurchasePage /> },
          { path: "purchase-complete", element: <PurchaseCompletePage /> },
          { path: "resale", element: <ResaleListPage /> },
          { path: "resale/:listingId", element: <ResaleDetailPage /> },
          { path: "me", element: <UserMyPage /> },
          { path: "tickets", element: <MyTicketListPage /> },
          { path: "tickets/:ticketId", element: <TicketDetailPage /> },
          { path: "tickets/:ticketId/resale", element: <TicketResaleCreatePage /> },
          { path: "resale-complete", element: <ResaleRegisterCompletePage /> },
          { path: "tickets/:ticketId/qr", element: <TicketQrPage /> },
        ],
      },
      {
        path: "organizer",
        element: <OrganizerAppLayout />,
        children: [
          { path: "start", element: <OrganizerLandingPage /> },
          { path: "auth", element: <OrganizerAuthPage /> },
          { index: true, element: <OrganizerDashboardPage /> },
          { path: "events/new", element: <EventCreatePage /> },
          { path: "events", element: <OrganizerEventListPage /> },
          { path: "events/:eventId", element: <OrganizerEventDetailPage /> },
          { path: "events/:eventId/settings", element: <EventSettingsPage /> },
          { path: "events/:eventId/sales", element: <SalesStatusPage /> },
          { path: "events/:eventId/checkins", element: <CheckInManagePage /> },
          { path: "events/:eventId/tickets/issue", element: <TicketIssuePage /> },
          { path: "me", element: <OrganizerProfilePage /> },
        ],
      },
      { path: "admin/login", element: <AdminLoginPage /> },
      { path: "admin", element: <AdminDashboardPage /> },
      { path: "admin/organizer-approvals", element: <OrganizerApprovalPage /> },
      { path: "admin/events", element: <AdminEventManagePage /> },
      { path: "admin/users", element: <AdminUserManagePage /> },
      { path: "admin/disputes", element: <AdminDisputeTransactionPage /> },
      { path: "admin/blockchain", element: <AdminBlockchainLogPage /> },

      { path: "user", element: <UserHomePage /> },
      { path: "user/events/:eventId", element: <EventDetailPage /> },
      { path: "user/resale", element: <ResaleListPage /> },
      { path: "user/resale/:listingId", element: <ResaleDetailPage /> },
      { path: "user/me", element: <UserMyPage /> },
      { path: "user/tickets/:ticketId", element: <TicketDetailPage /> },
      { path: "user/tickets", element: <MyTicketListPage /> },
      { path: "user/tickets/:ticketId/resale", element: <TicketResaleCreatePage /> },

    ],
  },
];
